/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.betancur.view;

import com.betancur.Disciplina;
import com.betancur.view.resources.TablaAspirantesModel;
import com.betancur.view.resources.TablaCategoriaModel;
import com.betancur.view.resources.TablaDisciplinasModel;
import com.betancur.view.resources.TablaEscuelasModel;
import com.betancur.view.resources.TablaEscuelasModelListener;
import com.betancur.vo.AspiranteVO;
import com.betancur.Escuela;
import com.betancur.controller.GestorDeInscripcion;
import com.betancur.view.resources.ResaltadorDeTabla;
import com.betancur.vo.DisciplinaVO;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;

/**
 *
 * @author Ariel
 */
public class UIRegistrarAspirante extends javax.swing.JFrame {
    private final GestorDeInscripcion controlador;
    
    //aspirantes con lista de competencias seleccionadas
    private final List <AspiranteVO> aspirantes;
    
    private AspiranteVO aspiranteSeleccionadoVO;
    private DisciplinaVO disciplinaSeleccionadaVO;
    
    private final TablaEscuelasModel tablaEscuelasModel;
    private final TablaAspirantesModel tablaAspirantesModel;
    private final TablaDisciplinasModel tablaDisciplinasModel;
    private final TablaCategoriaModel tablaCategoriasModel;
    
    /**
     * Creates new form UIRegistrarAspirante
     * @param controlador
     */
    public UIRegistrarAspirante(GestorDeInscripcion controlador) {
        this.controlador = controlador;
        this.aspirantes = new ArrayList<>();
        
        this.setResizable(false);
        
        //Crea los modelos de las tablas
        //cada tabla tiene el model asociado en Desing
        this.tablaEscuelasModel = new TablaEscuelasModel();
                
        this.tablaAspirantesModel = new TablaAspirantesModel();
        
        this.tablaDisciplinasModel = new TablaDisciplinasModel();
        
        this.tablaCategoriasModel = new TablaCategoriaModel();
        
        
        initComponents();
        
        
        jbtn_confirmarCategoriaDisciplina.setEnabled(false);
                
        jbtn_confirmarDisciplinas.setEnabled(false);
        
        //agrega escuchadores de las tablas
        tablaEscuelas.getSelectionModel().addListSelectionListener(new TablaEscuelasModelListener(this));
                
        tablaDisciplinasModel.visualizar(getTablaDisciplinas());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEscuelas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEscuelas = new javax.swing.JTable();
        panelAspirantes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAspirantes = new javax.swing.JTable();
        jbtn_nuevoAspirante = new javax.swing.JButton();
        panelCompetencias = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaDisciplinas = new javax.swing.JTable();
        jbtn_confirmarDisciplinas = new javax.swing.JButton();
        panelCategorias = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaCategorias = new javax.swing.JTable();
        jbtn_confirmarCategoriaDisciplina = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Aspirantes");

        panelEscuelas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccione una Entidad Educativa...", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tablaEscuelas.setModel(tablaEscuelasModel);
        jScrollPane1.setViewportView(tablaEscuelas);

        javax.swing.GroupLayout panelEscuelasLayout = new javax.swing.GroupLayout(panelEscuelas);
        panelEscuelas.setLayout(panelEscuelasLayout);
        panelEscuelasLayout.setHorizontalGroup(
            panelEscuelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEscuelasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelEscuelasLayout.setVerticalGroup(
            panelEscuelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEscuelasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelAspirantes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aspirantes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tablaAspirantes.setModel(tablaAspirantesModel);
        jScrollPane2.setViewportView(tablaAspirantes);

        jbtn_nuevoAspirante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtn_nuevoAspirante.setText("Nuevo Aspirante");
        jbtn_nuevoAspirante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_nuevoAspiranteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAspirantesLayout = new javax.swing.GroupLayout(panelAspirantes);
        panelAspirantes.setLayout(panelAspirantesLayout);
        panelAspirantesLayout.setHorizontalGroup(
            panelAspirantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAspirantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAspirantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAspirantesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtn_nuevoAspirante)))
                .addContainerGap())
        );
        panelAspirantesLayout.setVerticalGroup(
            panelAspirantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAspirantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtn_nuevoAspirante, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        panelCompetencias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Competencias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tablaDisciplinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaDisciplinas);

        jbtn_confirmarDisciplinas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtn_confirmarDisciplinas.setText("Confirmar Disciplinas");

        javax.swing.GroupLayout panelCompetenciasLayout = new javax.swing.GroupLayout(panelCompetencias);
        panelCompetencias.setLayout(panelCompetenciasLayout);
        panelCompetenciasLayout.setHorizontalGroup(
            panelCompetenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompetenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCompetenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(jbtn_confirmarDisciplinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCompetenciasLayout.setVerticalGroup(
            panelCompetenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompetenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_confirmarDisciplinas))
        );

        panelCategorias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categorias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tablaCategorias.setModel(tablaCategoriasModel);
        jScrollPane4.setViewportView(tablaCategorias);

        jbtn_confirmarCategoriaDisciplina.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtn_confirmarCategoriaDisciplina.setText("Confirmar Categoria");

        javax.swing.GroupLayout panelCategoriasLayout = new javax.swing.GroupLayout(panelCategorias);
        panelCategorias.setLayout(panelCategoriasLayout);
        panelCategoriasLayout.setHorizontalGroup(
            panelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(jbtn_confirmarCategoriaDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCategoriasLayout.setVerticalGroup(
            panelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_confirmarCategoriaDisciplina)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAceptar.setText("Aceptar");
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelEscuelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelAspirantes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAceptar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelCompetencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEscuelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelCompetencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelAspirantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jbtn_nuevoAspiranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_nuevoAspiranteActionPerformed
        
        if (!controlador.listarEscuelas().isEmpty()) {
             //carga las escuelas
            this.tablaEscuelasModel.setEscuelas(controlador.listarEscuelas());
            //actualiza el model
            tablaEscuelasModel.fireTableDataChanged();
            this.jbtn_nuevoAspirante.setEnabled(false);
        }else{
            //si no hay escuelas el boton esta habilitado
            this.jbtn_nuevoAspirante.setEnabled(true);
        }
    }//GEN-LAST:event_jbtn_nuevoAspiranteActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        //registra todos los aspirantes en sus respectivas competiciones seleccionadas
    }//GEN-LAST:event_btnAceptarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbtn_confirmarCategoriaDisciplina;
    private javax.swing.JButton jbtn_confirmarDisciplinas;
    private javax.swing.JButton jbtn_nuevoAspirante;
    private javax.swing.JPanel panelAspirantes;
    private javax.swing.JPanel panelCategorias;
    private javax.swing.JPanel panelCompetencias;
    private javax.swing.JPanel panelEscuelas;
    private javax.swing.JTable tablaAspirantes;
    private javax.swing.JTable tablaCategorias;
    private javax.swing.JTable tablaDisciplinas;
    private javax.swing.JTable tablaEscuelas;
    // End of variables declaration//GEN-END:variables

    public JTable getTablaDisciplinas() {
        return tablaDisciplinas;
    }

    public Escuela seleccionarEscuela () {
        Escuela retorno = null;
        int filaSeleccionada = tablaEscuelas.getSelectedRow();        
        // validamos que haya una fila seleccionada
        if (filaSeleccionada >= 0) {
            retorno = tablaEscuelasModel.obtenerEscuelaEn(filaSeleccionada);            
        }
        return retorno;
    }
    
    
    
    /**
     * Obtiene la posicion de la fila con el aspirante ingresado
     * @param aspiranteSeleccionado
     * @return 
     */
    public int seleccionarFilaEnTablaAspirante(AspiranteVO aspiranteSeleccionado){
        int retorno = 0;
        int cantidadRegistro = tablaAspirantes.getRowCount();
        // validamos que hayan registros en la tabla
        if (cantidadRegistro >= 0) {
            retorno = tablaAspirantesModel.obtenerAspiranteEn(aspiranteSeleccionado);            
        }
        return retorno;
    }
    
    public void pintarFilaTablaAspirante(int filaSeleccionada){
        ResaltadorDeTabla rst = new ResaltadorDeTabla(filaSeleccionada);
        this.tablaAspirantes.setDefaultRenderer(Object.class, rst);
    }
    
    public int seleccionarFilaEnTablaDisciplina(AspiranteVO aspirante){
        int retorno = 0;
        int cantidadRegistro = tablaDisciplinas.getRowCount();
        // validamos que hayan registros en la tabla
        if (cantidadRegistro >= 0) {
            //obtiene la primera disciplina activa
            retorno = tablaDisciplinasModel.obtenerLaPrimeraDisciplinaActivaEn(aspirante);            
        }
        return retorno;
    }
    
    public void pintarFilaTablaDisciplina(int filaSeleccionada){
        ResaltadorDeTabla rst = new ResaltadorDeTabla(filaSeleccionada);
        this.tablaDisciplinas.setDefaultRenderer(Object.class, rst);
    }
    
    public int seleccionarFilaEnTablaCategoria(DisciplinaVO disciplina){
        int retorno = 0;
        int cantidadRegistro = tablaCategorias.getRowCount();
        // validamos que hayan registros en la tabla
        if (cantidadRegistro >= 0) {
            //obtiene la primera disciplina activa
            retorno = tablaCategoriasModel.obtenerFilaDeCategoriaDeDisciplinaActiva(disciplina); 
        }
        return retorno;
    }
    
    public void pintarFilaTablaCategoria(int filaSeleccionada){
        ResaltadorDeTabla rst = new ResaltadorDeTabla(filaSeleccionada);
        this.tablaCategorias.setDefaultRenderer(Object.class, rst);
    }
    

    public TablaEscuelasModel getTablaEscuelasModel() {
        return tablaEscuelasModel;
    }

    public GestorDeInscripcion getControlador() {
        return controlador;
    }

    public javax.swing.JTable getTablaEscuelas() {
        return tablaEscuelas;
    }

    public List <AspiranteVO> getAspirantes() {
        return aspirantes;
    }

    public javax.swing.JTable getTablaAspirantes() {
        return tablaAspirantes;
    }

    public void setTablaAspirantes(javax.swing.JTable tablaAspirantes) {
        this.tablaAspirantes = tablaAspirantes;
    }

    public javax.swing.JTable getTablaCategorias() {
        return tablaCategorias;
    }

    public void setTablaCategorias(javax.swing.JTable tablaCategorias) {
        this.tablaCategorias = tablaCategorias;
    }

    public TablaAspirantesModel getTablaAspirantesModel() {
        return tablaAspirantesModel;
    }

    public TablaDisciplinasModel getTablaDisciplinasModel() {
        return tablaDisciplinasModel;
    }

    public TablaCategoriaModel getTablaCategoriasModel() {
        return tablaCategoriasModel;
    }

    public javax.swing.JButton getBtnAceptar() {
        return btnAceptar;
    }

    public javax.swing.JButton getBtnCancelar() {
        return btnCancelar;
    }

    public javax.swing.JButton getJbtn_confirmarCategoriaDisciplina() {
        return jbtn_confirmarCategoriaDisciplina;
    }

    public javax.swing.JButton getJbtn_confirmarDisciplinas() {
        return jbtn_confirmarDisciplinas;
    }

    public javax.swing.JButton getJbtn_nuevoAspirante() {
        return jbtn_nuevoAspirante;
    }

    public AspiranteVO getAspiranteSeleccionadoVO() {
        return aspiranteSeleccionadoVO;
    }

    public void setAspiranteSeleccionadoVO(AspiranteVO aspiranteSeleccionadoVO) {
        this.aspiranteSeleccionadoVO = aspiranteSeleccionadoVO;
    }

    public DisciplinaVO getDisciplinaSeleccionadaVO() {
        return disciplinaSeleccionadaVO;
    }

    public void setDisciplinaSeleccionadaVO(DisciplinaVO disciplinaSeleccionadaVO) {
        this.disciplinaSeleccionadaVO = disciplinaSeleccionadaVO;
    }
    
   
}
