/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.betancur.view;

import com.betancur.Categoria;
import com.betancur.Competencia;
import com.betancur.view.resources.TablaAspirantesModel;
import com.betancur.view.resources.TablaCategoriaModel;
import com.betancur.view.resources.TablaDisciplinasModel;
import com.betancur.view.resources.TablaEscuelasModel;
import com.betancur.view.resources.TablaEscuelasModelListener;
import com.betancur.vo.AspiranteVO;
import com.betancur.Escuela;
import com.betancur.Torneo;
import com.betancur.controller.GestorDeInscripcion;
import com.betancur.view.resources.ResaltadorDeTabla;
import com.betancur.view.resources.TablaAspirantesModelListener;
import com.betancur.vo.DisciplinaVO;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Ariel
 */
public class UIRegistrarAspirante extends javax.swing.JFrame {

    private final GestorDeInscripcion controlador;

    //aspirantes con lista de competencias seleccionadas
    private final List<AspiranteVO> aspirantes;
    private Torneo torneoActual;
    private int registrosTotalesDeAspirantes;
    private int registroActualDeAspirante;

    private int registrosTotalesDeDisciplinas;
    private int registroActualDeDisciplina;

    private int registroActualDeCategoria;

    private AspiranteVO aspiranteSeleccionadoVO;
    private DisciplinaVO disciplinaSeleccionadaVO;
    private Categoria categoriaSeleccionada;

    private final TablaEscuelasModel tablaEscuelasModel;
    private final TablaAspirantesModel tablaAspirantesModel;
    private final TablaDisciplinasModel tablaDisciplinasModel;
    private final TablaCategoriaModel tablaCategoriasModel;

    /**
     * Creates new form UIRegistrarAspirante
     *
     * @param controlador
     * @param torneo
     */
    public UIRegistrarAspirante(GestorDeInscripcion controlador, Torneo torneo) {
        this.controlador = controlador;
        this.aspirantes = new ArrayList<>();
        this.torneoActual = torneo;

        this.setResizable(false);

        //Crea los modelos de las tablas
        //cada tabla tiene el model asociado en Desing
        this.tablaEscuelasModel = new TablaEscuelasModel();

        this.tablaAspirantesModel = new TablaAspirantesModel();

        this.tablaDisciplinasModel = new TablaDisciplinasModel(this);

        this.tablaCategoriasModel = new TablaCategoriaModel();

        initComponents();

        jbtn_confirmarCategoriaDisciplina.setEnabled(false);

        jbtn_confirmarDisciplinas.setEnabled(false);

        //agrega escuchadores de las tablas
        tablaEscuelas.getSelectionModel().addListSelectionListener(new TablaEscuelasModelListener(this));

        tablaDisciplinasModel.visualizar(getTablaDisciplinas());

        //agrega escuchadores de las tabla Aspirante
        tablaAspirantes.getSelectionModel().addListSelectionListener(new TablaAspirantesModelListener(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEscuelas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEscuelas = new javax.swing.JTable();
        panelAspirantes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAspirantes = new javax.swing.JTable();
        jbtn_nuevoAspirante = new javax.swing.JButton();
        panelCompetencias = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaDisciplinas = new javax.swing.JTable();
        jbtn_confirmarDisciplinas = new javax.swing.JButton();
        panelCategorias = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaCategorias = new javax.swing.JTable();
        jbtn_confirmarCategoriaDisciplina = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Aspirantes");

        panelEscuelas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccione una Entidad Educativa...", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tablaEscuelas.setModel(tablaEscuelasModel);
        tablaEscuelas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tablaEscuelas);

        javax.swing.GroupLayout panelEscuelasLayout = new javax.swing.GroupLayout(panelEscuelas);
        panelEscuelas.setLayout(panelEscuelasLayout);
        panelEscuelasLayout.setHorizontalGroup(
            panelEscuelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEscuelasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelEscuelasLayout.setVerticalGroup(
            panelEscuelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEscuelasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelAspirantes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aspirantes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tablaAspirantes.setModel(tablaAspirantesModel);
        tablaAspirantes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tablaAspirantes);

        jbtn_nuevoAspirante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtn_nuevoAspirante.setText("Nuevo Aspirante");
        jbtn_nuevoAspirante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_nuevoAspiranteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAspirantesLayout = new javax.swing.GroupLayout(panelAspirantes);
        panelAspirantes.setLayout(panelAspirantesLayout);
        panelAspirantesLayout.setHorizontalGroup(
            panelAspirantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAspirantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAspirantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAspirantesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtn_nuevoAspirante)))
                .addContainerGap())
        );
        panelAspirantesLayout.setVerticalGroup(
            panelAspirantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAspirantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtn_nuevoAspirante, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        panelCompetencias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Competencias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tablaDisciplinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaDisciplinas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tablaDisciplinas);

        jbtn_confirmarDisciplinas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtn_confirmarDisciplinas.setText("Confirmar Disciplinas");
        jbtn_confirmarDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_confirmarDisciplinasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCompetenciasLayout = new javax.swing.GroupLayout(panelCompetencias);
        panelCompetencias.setLayout(panelCompetenciasLayout);
        panelCompetenciasLayout.setHorizontalGroup(
            panelCompetenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompetenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCompetenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(jbtn_confirmarDisciplinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCompetenciasLayout.setVerticalGroup(
            panelCompetenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompetenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_confirmarDisciplinas))
        );

        panelCategorias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categorias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tablaCategorias.setModel(tablaCategoriasModel);
        tablaCategorias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(tablaCategorias);

        jbtn_confirmarCategoriaDisciplina.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtn_confirmarCategoriaDisciplina.setText("Confirmar Categoria");
        jbtn_confirmarCategoriaDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_confirmarCategoriaDisciplinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCategoriasLayout = new javax.swing.GroupLayout(panelCategorias);
        panelCategorias.setLayout(panelCategoriasLayout);
        panelCategoriasLayout.setHorizontalGroup(
            panelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(jbtn_confirmarCategoriaDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCategoriasLayout.setVerticalGroup(
            panelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_confirmarCategoriaDisciplina)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAceptar.setText("Aceptar");
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelEscuelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelAspirantes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAceptar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelCompetencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEscuelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelCompetencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelAspirantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param evt
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     *
     * @param evt
     */
    private void jbtn_nuevoAspiranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_nuevoAspiranteActionPerformed

        if (!controlador.listarEscuelas().isEmpty()) {
            //carga las escuelas
            this.tablaEscuelasModel.setEscuelas(controlador.listarEscuelas());
            //actualiza el model
            tablaEscuelasModel.fireTableDataChanged();
            this.jbtn_nuevoAspirante.setEnabled(false);
        } else {
            //si no hay escuelas el boton esta habilitado
            this.jbtn_nuevoAspirante.setEnabled(true);
        }
    }//GEN-LAST:event_jbtn_nuevoAspiranteActionPerformed

    /**
     *
     * @param evt
     */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        Competencia c = new Competencia();

        for (AspiranteVO aspirante : aspirantes) {
            System.out.println("aspirante: " + aspirante.getAspirante().getNombres());
            for (DisciplinaVO disciplinaRecorrido : aspirante.getDisciplinas()) {
                if (disciplinaRecorrido.getDisciplina().getTorneo() != null) {

                    c = controlador.buscarCometetenciaDeDisciplinaConCategoria(disciplinaRecorrido.getDisciplina(), disciplinaRecorrido.getCategoria());

                    System.out.println("disciplina id: " + disciplinaRecorrido.getDisciplina().getId());
                    System.out.println("disciplina id_categoria: " + disciplinaRecorrido.getCategoria().getId());

                    System.out.println("id competencia id_disciplina: " + c.getDisciplina().getId());
                    System.out.println("id competencia id_Categoria: " + c.getCategoria().getId());
                }

            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     *
     * @param evt
     */
    private void jbtn_confirmarDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_confirmarDisciplinasActionPerformed

        tablaDisciplinasModel.fireTableDataChanged();
        //aspiranteSeleccionadoVO.setDisciplinas(tablaDisciplinasModel.getDisciplinas());

        getTablaDisciplinas().setEnabled(false);
        getJbtn_confirmarDisciplinas().setEnabled(false);
        setRegistroActualDeAspirante(getRegistroActualDeAspirante() + 1);
        if (getRegistroActualDeAspirante() < getRegistrosTotalesDeAspirantes()) {
            //posiciona las tablas
            seleccionarTablas(getRegistroActualDeAspirante());
            //se llama a si mismo
            modificarDisciplinas(getAspirantes().get(getRegistroActualDeAspirante()));

        } else {//Llega al final de la lista
            System.out.println("llego al final por el boton");

            //posiciona las tablas en el primer registro
            seleccionarTablas(0);

            //setea los registros a recorrer
            setRegistrosTotalesDeAspirantes(getAspirantes().size());
            //Setea el primer registro
            setRegistroActualDeAspirante(0);

            //setea las disciplinas del 1er aspitante
            setRegistrosTotalesDeDisciplinas(calcularRegistrosTotalesDeDisciplinas(getAspiranteSeleccionadoVO().getDisciplinas()));

            modificarCategoriasDeDisciplinas(getAspiranteSeleccionadoVO());
        }


    }//GEN-LAST:event_jbtn_confirmarDisciplinasActionPerformed

    /**
     *
     * @param evt
     */
    private void jbtn_confirmarCategoriaDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_confirmarCategoriaDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_confirmarCategoriaDisciplinaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbtn_confirmarCategoriaDisciplina;
    private javax.swing.JButton jbtn_confirmarDisciplinas;
    private javax.swing.JButton jbtn_nuevoAspirante;
    private javax.swing.JPanel panelAspirantes;
    private javax.swing.JPanel panelCategorias;
    private javax.swing.JPanel panelCompetencias;
    private javax.swing.JPanel panelEscuelas;
    private javax.swing.JTable tablaAspirantes;
    private javax.swing.JTable tablaCategorias;
    private javax.swing.JTable tablaDisciplinas;
    private javax.swing.JTable tablaEscuelas;
    // End of variables declaration//GEN-END:variables


    /*
     *--------------------------------------------------------------------------
     *Setters y Getters Componentes
     *--------------------------------------------------------------------------
     */
    public javax.swing.JButton getBtnAceptar() {
        return btnAceptar;
    }

    public javax.swing.JButton getBtnCancelar() {
        return btnCancelar;
    }

    public javax.swing.JButton getJbtn_confirmarCategoriaDisciplina() {
        return jbtn_confirmarCategoriaDisciplina;
    }

    public javax.swing.JButton getJbtn_confirmarDisciplinas() {
        return jbtn_confirmarDisciplinas;
    }

    public javax.swing.JButton getJbtn_nuevoAspirante() {
        return jbtn_nuevoAspirante;
    }

    public javax.swing.JTable getTablaAspirantes() {
        return tablaAspirantes;
    }

    public void setTablaAspirantes(javax.swing.JTable tablaAspirantes) {
        this.tablaAspirantes = tablaAspirantes;
    }

    public javax.swing.JTable getTablaCategorias() {
        return tablaCategorias;
    }

    public void setTablaCategorias(javax.swing.JTable tablaCategorias) {
        this.tablaCategorias = tablaCategorias;
    }

    public JTable getTablaDisciplinas() {
        return tablaDisciplinas;
    }

    public javax.swing.JTable getTablaEscuelas() {
        return tablaEscuelas;
    }

    /*
     *--------------------------------------------------------------------------
     *Setters y Getters Variables
     *--------------------------------------------------------------------------
     */
    public GestorDeInscripcion getControlador() {
        return controlador;
    }

    public List<AspiranteVO> getAspirantes() {
        return aspirantes;
    }

    public Torneo getTorneoActual() {
        return torneoActual;
    }

    public void setTorneoActual(Torneo torneoActual) {
        this.torneoActual = torneoActual;
    }

    public int getRegistrosTotalesDeAspirantes() {
        return registrosTotalesDeAspirantes;
    }

    public void setRegistrosTotalesDeAspirantes(int registrosTotalesDeAspirantes) {
        this.registrosTotalesDeAspirantes = registrosTotalesDeAspirantes;
    }

    public int getRegistroActualDeAspirante() {
        return registroActualDeAspirante;
    }

    public void setRegistroActualDeAspirante(int registroActualDeAspirante) {
        this.registroActualDeAspirante = registroActualDeAspirante;
    }

    public int getRegistrosTotalesDeDisciplinas() {
        return registrosTotalesDeDisciplinas;
    }

    public void setRegistrosTotalesDeDisciplinas(int registrosTotalesDeDisciplinas) {
        this.registrosTotalesDeDisciplinas = registrosTotalesDeDisciplinas;
    }

    public int getRegistroActualDeDisciplina() {
        return registroActualDeDisciplina;
    }

    public void setRegistroActualDeDisciplina(int registroActualDeDisciplina) {
        this.registroActualDeDisciplina = registroActualDeDisciplina;
    }

    public int getRegistroActualDeCategoria() {
        return registroActualDeCategoria;
    }

    public void setRegistroActualDeCategoria(int registroActualDeCategoria) {
        this.registroActualDeCategoria = registroActualDeCategoria;
    }

    public AspiranteVO getAspiranteSeleccionadoVO() {
        return aspiranteSeleccionadoVO;
    }

    public void setAspiranteSeleccionadoVO(AspiranteVO aspiranteSeleccionadoVO) {
        this.aspiranteSeleccionadoVO = aspiranteSeleccionadoVO;
    }

    public DisciplinaVO getDisciplinaSeleccionadaVO() {
        return disciplinaSeleccionadaVO;
    }

    public void setDisciplinaSeleccionadaVO(DisciplinaVO disciplinaSeleccionadaVO) {
        this.disciplinaSeleccionadaVO = disciplinaSeleccionadaVO;
    }

    public Categoria getCategoriaSeleccionada() {
        return categoriaSeleccionada;
    }

    public void setCategoriaSeleccionada(Categoria categoriaSeleccionada) {
        this.categoriaSeleccionada = categoriaSeleccionada;
    }

    public TablaEscuelasModel getTablaEscuelasModel() {
        return tablaEscuelasModel;
    }

    public TablaAspirantesModel getTablaAspirantesModel() {
        return tablaAspirantesModel;
    }

    public TablaDisciplinasModel getTablaDisciplinasModel() {
        return tablaDisciplinasModel;
    }

    public TablaCategoriaModel getTablaCategoriasModel() {
        return tablaCategoriasModel;
    }


    /*
     *--------------------------------------------------------------------------
     *--------------------------------------------------------------------------
     *Metodos Especificos
     *--------------------------------------------------------------------------
     */
 /*
     *--------------------------------------------------------------------------
     *-------------------------Tabla Escuela------------------------------------
     *--------------------------------------------------------------------------
     */
    public Escuela seleccionarEscuela() {
        Escuela retorno = null;
        int filaSeleccionada = tablaEscuelas.getSelectedRow();
        // validamos que haya una fila seleccionada
        if (filaSeleccionada >= 0) {
            retorno = tablaEscuelasModel.obtenerEscuelaEn(filaSeleccionada);
        }
        return retorno;
    }

    /*
     *--------------------------------------------------------------------------
     *-------------------------Tabla Aspirante----------------------------------
     *--------------------------------------------------------------------------
     */
    /**
     * Configura la tabla Aspirante, Disciplina y Categoria, segun el aspirante
     * actual seleccionado
     *
     * @param seleccionAspirante
     */
    public void seleccionarTablas(int seleccionAspirante) {
        /**
         * Configuración tabla Aspirantes
         */
        //Selecciona al aspirante segun la posicion de fila ingresada
        setAspiranteSeleccionadoVO(getAspirantes().get(seleccionAspirante));
        //pinta el  aspirante seleccionado
        pintarFilaTablaAspirante(seleccionarFilaEnTablaAspirante(getAspiranteSeleccionadoVO()) - 1);
        //Actualiza la tabla Aspirante
        getTablaAspirantesModel().fireTableDataChanged();

        /**
         * Configuración de la tabla Disciplinas
         */
        //Agrega las disciplinas del aspirante seleccionado
        getTablaDisciplinasModel().setDisciplinas(getAspiranteSeleccionadoVO().getDisciplinas());
        //Actualiza la tabla Disciplina   
        getTablaDisciplinasModel().visualizar(getTablaDisciplinas());
        //inhabilita la seleccion de la tabla Disciplina
        getTablaDisciplinas().setEnabled(false);
        //selecciona la fila correspondiente al nuevo aspirante seleccionado
        this.registroActualDeDisciplina = seleccionarFilaEnTablaDisciplina(getAspiranteSeleccionadoVO()) - 1;
        //Settea la Disciplina actual seleccionada 
        setDisciplinaSeleccionadaVO(getTablaDisciplinasModel().obtenerDisciplinaEn(registroActualDeDisciplina));
        //pinta la primera fila de la disciplina seleccionada
        pintarFilaTablaDisciplina(registroActualDeDisciplina);

        /**
         * Configuración de la tabla Categorias
         */
        //agrega todas Categorias 
        getTablaCategoriasModel().setCategorias(getControlador().listarCategorias());
        //Actualiza la tabla Categoria       
        getTablaCategoriasModel().fireTableDataChanged();
        //inhabilita la seleccion de la tabla Categoria
        getTablaCategorias().setEnabled(false);
        //Selecciona la categoria de la primera disciplina seleccionada del aspirante ingresado              
        this.registroActualDeCategoria = seleccionarFilaEnTablaCategoria(getDisciplinaSeleccionadaVO()) - 1;
        //pinta la categoria de la primera disciplina seleccionada del aspirante ingresado 
        pintarFilaTablaCategoria(this.registroActualDeCategoria);

    }

    public int seleccionarFilaEnTablaAspirante(AspiranteVO aspiranteSeleccionado) {
        int retorno = 0;
        int cantidadRegistro = tablaAspirantes.getRowCount();
        // validamos que hayan registros en la tabla
        if (cantidadRegistro >= 0) {
            retorno = tablaAspirantesModel.obtenerAspiranteEn(aspiranteSeleccionado);
        }
        return retorno;
    }

    public void pintarFilaTablaAspirante(int filaSeleccionada) {
        ResaltadorDeTabla rst = new ResaltadorDeTabla(filaSeleccionada);
        this.tablaAspirantes.setDefaultRenderer(Object.class, rst);
    }

    public void agregarAspiranteATabla(AspiranteVO nuevoAspiranteVO) {
        int primeraDisciplina = 0;
        int categoriaDeDisciplina = 0;

        /**
         * Configuración tabla Aspirantes
         */
        //Agrega el aspirante a la lista de aspirantes a registrar (ValueObject necesarios)
        getAspirantes().add(nuevoAspiranteVO);
        //Seleccionar AspiranteVO actual
        setAspiranteSeleccionadoVO(nuevoAspiranteVO);

        /**
         * Configuración de la tabla Aspirantes
         */
        //agrega a la tabla de aspirante el nuevo aspirante
        getTablaAspirantesModel().setAspirantes(getAspirantes());
        //pinta el nuevo aspirante en la tabla aspirantes
        pintarFilaTablaAspirante(seleccionarFilaEnTablaAspirante(nuevoAspiranteVO) - 1);
        //actualiza el TableModel para que se refresque la tabla
        getTablaAspirantesModel().fireTableDataChanged();
        //inhabilita la seleccion de la tabla aspirante
        getTablaAspirantes().setEnabled(false);

        /**
         * Configuración de la tabla Disciplinas
         */
        //Agrega a la tabla Disciplina, las disciplinas del nuevo aspirante
        getTablaDisciplinasModel().setDisciplinas(nuevoAspiranteVO.getDisciplinas());
        //actualiza el TableModel para que se refresque la tabla     
        getTablaDisciplinasModel().visualizar(getTablaDisciplinas());
        //inhabilita la seleccion de la tabla Disciplina
        getTablaDisciplinas().setEnabled(false);
        //selecciona la primera fila de la disciplina del nuevo aspirante
        primeraDisciplina = seleccionarFilaEnTablaDisciplina(nuevoAspiranteVO) - 1;
        //Agrega la Disciplina Seleccionada  
        setDisciplinaSeleccionadaVO(getTablaDisciplinasModel().obtenerDisciplinaEn(primeraDisciplina));
        //pinta la primera fila seleccionada de la disciplina
        pintarFilaTablaDisciplina(primeraDisciplina);

        /**
         * Configuración de la tabla Categorias
         */
        //agrega a la tabla el Categoria, todas las categorias
        getTablaCategoriasModel().setCategorias(getControlador().listarCategorias());
        //actualiza el model para que se refresque la tabla        
        getTablaCategoriasModel().fireTableDataChanged();
        //inhabilita la seleccion de la tabla Categoria
        getTablaCategorias().setEnabled(false);
        //selecciona la categoria de la primera disciplina del nuevo aspirante                
        categoriaDeDisciplina = seleccionarFilaEnTablaCategoria(getDisciplinaSeleccionadaVO()) - 1;
        //pinta la categoria de la primera disciplina del nuevo aspirante
        pintarFilaTablaCategoria(categoriaDeDisciplina);
    }

    /*
     *--------------------------------------------------------------------------
     *-------------------------Tabla Disciplina---------------------------------
     *--------------------------------------------------------------------------
     */
    public DisciplinaVO seleccionarDisciplina() {
        DisciplinaVO retorno = null;
        int filaSeleccionada = tablaDisciplinas.getSelectedRow();
        // validamos que haya una fila seleccionada
        if (filaSeleccionada >= 0) {
            retorno = tablaDisciplinasModel.obtenerDisciplinaEn(filaSeleccionada);
        }
        return retorno;

    }

    public DisciplinaVO seleccionarDisciplinaPorFila(int fila) {
        DisciplinaVO retorno = tablaDisciplinasModel.getDisciplinas().get(fila);

        return retorno;

    }

    public int seleccionarFilaEnTablaDisciplina(AspiranteVO aspirante) {
        int retorno = 0;
        int cantidadRegistro = tablaDisciplinas.getRowCount();
        // validamos que hayan registros en la tabla
        if (cantidadRegistro >= 0) {
            //obtiene la primera disciplina activa
            retorno = tablaDisciplinasModel.obtenerLaPrimeraDisciplinaActivaEn(aspirante);
        }
        return retorno;
    }

    public int obtenerFilaDeDisciplina(AspiranteVO aspiranteVOActual, DisciplinaVO disciplinaVoActual) {
        int retorno = tablaDisciplinasModel.obtenerFilaDeDisciplina(aspiranteVOActual, disciplinaSeleccionadaVO);
        return retorno;
    }

    public void pintarFilaTablaDisciplina(int filaSeleccionada) {
        ResaltadorDeTabla rst = new ResaltadorDeTabla(filaSeleccionada);
        this.tablaDisciplinas.setDefaultRenderer(Object.class, rst);
    }

    public void modificarDisciplinas(AspiranteVO aspiranteVO) {

        if (getRegistrosTotalesDeAspirantes() > 0 && getRegistroActualDeAspirante() < getRegistrosTotalesDeAspirantes()) {
            int faseModificacionDisciplina = JOptionPane.showConfirmDialog(this, "¿Desea Modificar las Disciplinas por Defecto? \n del aspirante " + aspiranteVO.getAspirante().getNombres() + " " + aspiranteVO.getAspirante().getApellido(), "Modificar Categoria!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

            if (faseModificacionDisciplina == 0) {//SI
                System.out.println("Modifica");
                getTablaDisciplinas().setEnabled(true);
                getJbtn_confirmarDisciplinas().setEnabled(true);

            } else {//NO --Pasa al siguiente
                getTablaDisciplinas().setEnabled(false);
                getJbtn_confirmarDisciplinas().setEnabled(false);
                setRegistroActualDeAspirante(getRegistroActualDeAspirante() + 1);
                if (getRegistroActualDeAspirante() < getRegistrosTotalesDeAspirantes()) {
                    //posiciona las tablas
                    seleccionarTablas(getRegistroActualDeAspirante());
                    //se llama a si mismo
                    modificarDisciplinas(getAspirantes().get(getRegistroActualDeAspirante()));

                } else {//Llega al final de la lista
                    System.out.println("llego al final por el proceso");

                    //posiciona las tablas en el primer registro
                    seleccionarTablas(0);

                    //setea los registros a recorrer
                    setRegistrosTotalesDeAspirantes(getAspirantes().size());
                    //Setea el primer registro
                    setRegistroActualDeAspirante(0);

                    //setea las disciplinas del 1er aspitante
                    setRegistrosTotalesDeDisciplinas(calcularRegistrosTotalesDeDisciplinas(getAspiranteSeleccionadoVO().getDisciplinas()));

                    modificarCategoriasDeDisciplinas(getAspiranteSeleccionadoVO());

                }

            }
        } else {
            System.out.println("no hay registros");
        }

    }

    public int calcularRegistrosTotalesDeDisciplinas(List<DisciplinaVO> disciplinas) {
        int cantidadDisciplinasSeleccionadas = 0;
        for (DisciplinaVO disciplina : disciplinas) {
            if (disciplina.getActivo()) {
                cantidadDisciplinasSeleccionadas = cantidadDisciplinasSeleccionadas + 1;
            }
        }

        return cantidadDisciplinasSeleccionadas;
    }

    public void pintarDisciplinaConCategoria(int fila){
        
        /**asd
         * Configuración de la tabla Disciplinas
         */
        //Agrega las disciplinas del aspirante seleccionado
        getTablaDisciplinasModel().setDisciplinas(getAspiranteSeleccionadoVO().getDisciplinas());
        //Actualiza la tabla Disciplina   
        getTablaDisciplinasModel().visualizar(getTablaDisciplinas());
        //inhabilita la seleccion de la tabla Disciplina
        getTablaDisciplinas().setEnabled(false);
        
        //Settea la Disciplina actual seleccionada 
        setDisciplinaSeleccionadaVO(getTablaDisciplinasModel().obtenerDisciplinaEn(registroActualDeDisciplina));
        //pinta la primera fila de la disciplina seleccionada
        pintarFilaTablaDisciplina(registroActualDeDisciplina);

        /**
         * Configuración de la tabla Categorias
         */
        //agrega todas Categorias 
        getTablaCategoriasModel().setCategorias(getControlador().listarCategorias());
        //Actualiza la tabla Categoria       
        getTablaCategoriasModel().fireTableDataChanged();
        //inhabilita la seleccion de la tabla Categoria
        getTablaCategorias().setEnabled(false);
        //Selecciona la categoria de la primera disciplina seleccionada del aspirante ingresado              
        this.registroActualDeCategoria = seleccionarFilaEnTablaCategoria(getDisciplinaSeleccionadaVO()) - 1;
        //pinta la categoria de la primera disciplina seleccionada del aspirante ingresado 
        pintarFilaTablaCategoria(this.registroActualDeCategoria);
    }

    /*
     *--------------------------------------------------------------------------
     *-------------------------Tabla Categoria----------------------------------
     *--------------------------------------------------------------------------
     */
    public void seleccionarCategoriaDeDisciplina(int filaDisciplina) {

        //Setea la Disciplina segun la fila seleccionada 
        setDisciplinaSeleccionadaVO(getTablaDisciplinasModel().obtenerDisciplinaEn(filaDisciplina));
        //pinta la fila seleccionada de la disciplina
        pintarFilaTablaDisciplina(filaDisciplina);
        //Setea la categoria actual de la disciplina seleccionada                
        setRegistroActualDeCategoria(seleccionarFilaEnTablaCategoria(getDisciplinaSeleccionadaVO()) - 1);
        //pinta la categoria actual de la disciplina seleccionada   
        pintarFilaTablaCategoria(getRegistroActualDeCategoria());

    }

    public int seleccionarFilaEnTablaCategoria(DisciplinaVO disciplina) {
        int retorno = 0;
        int cantidadRegistro = tablaCategorias.getRowCount();
        // validamos que hayan registros en la tabla
        if (cantidadRegistro >= 0) {
            //obtiene la primera disciplina activa
            retorno = tablaCategoriasModel.obtenerFilaDeCategoriaDeDisciplinaActiva(disciplina);
        }
        return retorno;
    }

    public void pintarFilaTablaCategoria(int filaSeleccionada) {
        ResaltadorDeTabla rst = new ResaltadorDeTabla(filaSeleccionada);
        this.tablaCategorias.setDefaultRenderer(Object.class, rst);
    }

    //Mofificar Categoria
    public void modificarCategoriasDeDisciplinas(AspiranteVO aspiranteVO) {
        int proximaDisciplina = 0;
        

        System.out.println("fila de disciplina: " + obtenerFilaDeDisciplina(getAspiranteSeleccionadoVO(), getDisciplinaSeleccionadaVO()));
        //pintar disciplina actual
        pintarDisciplinaConCategoria(obtenerFilaDeDisciplina(getAspiranteSeleccionadoVO(), getDisciplinaSeleccionadaVO()));

        //aspirante actual
        if (getRegistrosTotalesDeAspirantes() > 0 && getRegistroActualDeAspirante() < getRegistrosTotalesDeAspirantes()) {

            //disciplina actual
            if (getRegistrosTotalesDeDisciplinas() > 0 && getRegistroActualDeDisciplina() < getRegistrosTotalesDeDisciplinas()) {
                int faseModificacionCategoria = JOptionPane.showConfirmDialog(this, "¿Desea Modificar la Categoria por Defecto? \n de la disciplina " + "'" + getDisciplinaSeleccionadaVO().getDisciplina().getNombre() + "'", "Modificar Categoria!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

                if (faseModificacionCategoria == 0) {//SI Modifica Categoria de Disciplina

                } else {//NO modifica y pasa a la siguiente disiplina
                    proximaDisciplina = getRegistroActualDeDisciplina() + 1;
                    if (proximaDisciplina < getRegistrosTotalesDeDisciplinas()) {
                        setRegistroActualDeDisciplina(proximaDisciplina);

                        setDisciplinaSeleccionadaVO(seleccionarDisciplinaPorFila(proximaDisciplina));
                        //posicionarDisciplina;

                        modificarCategoriasDeDisciplinas(this.getAspiranteSeleccionadoVO());
                    }else{
                        System.out.println("No hay mas disciplinas del aspirante");
                    }

                }

            } else {
                System.out.println("final de disciplinas del aspirante");
                //pasar al siguiente aspirante y llamar al metodo
            }

        } else {
            System.out.println("no hay registros");
        }

        /*
        
        setRegistroActualDeAspirante(getRegistroActualDeAspirante() + 1);
        if (getRegistroActualDeAspirante() < getRegistrosTotalesDeAspirantes()) {
            //posiciona las tablas
            seleccionarTablas(getRegistroActualDeAspirante());
        
        
        if (getRegistrosTotalesDeAspirantes() > 0 && getRegistroActualDeAspirante() < getRegistrosTotalesDeAspirantes()) {
            int faseModificacionCategoria = JOptionPane.showConfirmDialog(this, "¿Desea Modificar la Categoria por Defecto? \n del aspirante " + aspiranteVO.getAspirante().getNombres() + " " + aspiranteVO.getAspirante().getApellido(), "Modificar Categoria!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

            if (faseModificacionCategoria == 0) {//SI
                System.out.println("Modifica");
                getTablaCategorias().setEnabled(true);
                getJbtn_confirmarDisciplinas().setEnabled(true);

            } else {//NO --Pasa al siguiente Disciplina
                getTablaCategorias().setEnabled(false);
                getJbtn_confirmarCategoriaDisciplina().setEnabled(false);

                //disciplina actual seleccionada
                
                
                //setRegistroActualDeAspirante(getRegistroActualDeAspirante() + 1);

//                setRegistroActualDeAspirante(getRegistroActualDeAspirante() + 1);
//                if (getRegistroActualDeAspirante() < getRegistrosTotalesDeAspirantes()) {
//                    //posiciona las tablas
//                    seleccionarTablas(getRegistroActualDeAspirante());
//                    //se llama a si mismo
//                    modificarCategoriasDeDisciplinas(getAspirantes().get(getRegistroActualDeAspirante()));
//
//                } else {//Llega al final de la lista
//                    System.out.println("llego al final por el proceso");
//                    //llarmar al metodo modificarCategoria
//                    //aplicar nuevos metodos de verificación
//                }
            }
        } else {
            System.out.println("no hay registros");
        }
         */
    }

}
